version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: iluvcoffee_pgql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123

  test-db:
    image: postgres
    restart: always
    container_name: iluvcoffee_pgql_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123


